#DROP TABLE ATENCION_PRODUCTO;
#DROP TABLE PRODUCTO_MEDICO;
#DROP TABLE RECIBE_ATENCION;
#DROP TABLE ENFERMERA;
#DROP TABLE PACIENTE;
#ALTER TABLE PRODUCTO_MEDICO AUTO_INCREMENT = 1;

CHARACTER SET utf8mb4
COLLATE utf8mb4_spanish_ci;
# =========================================
CREATE TABLE IF NOT EXISTS USERS(
	U_ID INT PRIMARY KEY AUTO_INCREMENT,
	U_EID INT,
	U_User varchar(30) NOT NULL,
	U_Password CHAR(60) NOT NULL,
	U_ImgPath VARCHAR(30) DEFAULT ("default-user.png") NOT NULL,
	
	FOREIGN KEY (U_EID) REFERENCES ENFERMERA(EnfermeraID)
);

drop table TEMP_MEDIC;
CREATE TABLE TEMP_MEDIC(
ProductoID INT PRIMARY KEY AUTO_INCREMENT,
    Sustancia_activa VARCHAR(100),
	Cantidad_Sum int
    );

CREATE TABLE IF NOT EXISTS PRODUCTOS_MEDICOS(
    ProductoID INT PRIMARY KEY AUTO_INCREMENT,
    Status int(1) DEFAULT 1 not null check (Status in (0,1,2)),
    Clasificacion VARCHAR(30),
    Presentacion VARCHAR(30),
    Sustancia_activa VARCHAR(100),
    Cantidad INT(10),
    No_pastillas INT(10),
   	Elementos_res int,
    Sede VARCHAR(30),
    Fecha_caducidad DATE,
    Fecha_registro DATE
);

CREATE TABLE IF NOT EXISTS ENFERMERA(
    EnfermeraID INT AUTO_INCREMENT PRIMARY KEY,
    Apellido_pat VARCHAR(30),
    Apellido_mat VARCHAR(30),
    Nombre VARCHAR(30),
    Telefono VARCHAR(10)
);
CHARACTER SET utf8mb4
COLLATE utf8mb4_spanish_ci;

DROP TABLE PACIENTE;
CREATE TABLE IF NOT EXISTS PACIENTE(
    PacienteID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUA INT(6) CHECK (NUA >= 0),
    Nombre VARCHAR(30),
    Apellido_pat VARCHAR (30),
    Apellido_mat VARCHAR (30)
);
-- CREAR PACIENTE EXTERNO CON ID SIEMPRE 0
INSERT INTO PACIENTE (PacienteID,NUA,Nombre,Apellido_pat,Apellido_mat)VALUES(0,000000,"Externo","ApellidoX","ApellidoY");
UPDATE PACIENTE SET PacienteID = 0 WHERE PacienteID = 1; 
-- SELECT * FROM PACIENTE;
CHARACTER SET utf8mb4
COLLATE utf8mb4_spanish_ci;

CREATE TABLE IF NOT EXISTS RECIBE_ATENCION(
    AtencionID INT AUTO_INCREMENT PRIMARY KEY,
    Diagnostico VARCHAR(60),
    Fecha_hora DATETIME,
    EnfermeraID INT,
    PacienteID INT,
    FOREIGN KEY (EnfermeraID) REFERENCES ENFERMERA(EnfermeraID),
    FOREIGN KEY (PacienteID) REFERENCES PACIENTE(PacienteID)
);

CHARACTER SET utf8mb4
COLLATE utf8mb4_spanish_ci;

DROP TABLE ATENCION_PRODUCTO;
CREATE TABLE IF NOT EXISTS ATENCION_PRODUCTO(
    Atencion_productoID INT AUTO_INCREMENT PRIMARY KEY,
    AtencionID INT,
    ProductoID INT,
    Cantidad INT CHECK (Cantidad >=1),
    
    FOREIGN KEY (AtencionID) REFERENCES RECIBE_ATENCION(AtencionID),
    FOREIGN KEY (ProductoID) REFERENCES PRODUCTOS_MEDICOS(ProductoID)
);

CHARACTER SET utf8mb4
COLLATE utf8mb4_spanish_ci;

call SHOW_PRODUCTS();

CREATE USER 'webclient'@'%' IDENTIFIED BY '[PASSWORD]';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`DEL_Product` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`EDIT_PRODUCT` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`INS_PRODUCT` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`SHOW_PRODUCTS` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`GET_USER_BY_USERNAME` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`GET_PRODUCT` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`BuscarMedicamentos` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`GET_MediCart` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`ADD_MediCart` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`DEL_MediCart` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`ADD_ATENTION` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`Reset_Cart` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`INSERT_Report` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`GET_REPORT_BY_ID` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`SHOW_REPORTS` TO 'webclient'@'%';
GRANT EXECUTE ON PROCEDURE `UG-ENF`.`SHOW_NOTIFICATIONS` TO 'webclient'@'%';
FLUSH PRIVILEGES;